apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: fil-rouge
type: Opaque
stringData:
  MONGO_URI: "mongodb://root:changeme@mongo.fil-rouge.svc.cluster.local:27017/?authSource=admin"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: fil-rouge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: aychana/express-backend:latest
        ports:
        - containerPort: 5001
        envFrom:
        - secretRef:
            name: backend-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: fil-rouge
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - port: 5001
    targetPort: 5001